#Login as root on ansible controller

#mkdir -p /opt/ansible-demo

#cd /opt/ansible-demo

#vi sshcopy.yml

---
- hosts: all

  tasks:
    - name: Execute SSH-keygen
      command: ssh-keygen -y -t rsa -f /root/.ssh/id_rsa -N ''
      args:
        creates: /root/.ssh/id_rsa
      delegate_to: localhost

    - name: Set Authorized key token from file
      become: true
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"