---
- hosts: server  #group name from the inventory
  become: true

  vars:
    pack_name: httpd

  vars_files:
    - web_vars.yml

  tasks:
    - name: Install {{ pack_name }}
      yum: pkg={{ pack_name }} state=installed
    - name: Start {{ serv_name }}
      service: name={{ serv_name }} state=started
